#!/bin/bash

echo 'export AWS_ACCESS_KEY_ID='$AWS_ACCESS_KEY_ID > /root/setenv
echo 'export AWS_SECRET_ACCESS_KEY='$AWS_SECRET_ACCESS_KEY >> /root/setenv
echo 'export AWS_ACCOUNT_NUMBER='$AWS_ACCOUNT_NUMBER >> /root/setenv
echo 'export EC2_AMI_ID='$EC2_AMI_ID >> /root/setenv
echo 'export EC2_AKI_ID='$EC2_AKI_ID >> /root/setenv
echo 'export EC2_ARI_ID='$EC2_ARI_ID >> /root/setenv
echo 'export EC2_AMI_MANIFEST_PATH='$EC2_AMI_MANIFEST_PATH >> /root/setenv
echo 'export EC2_AVAILABILITY_ZONE='$EC2_AVAILABILITY_ZONE >> /root/setenv
echo 'export EC2_HOSTNAME='$EC2_HOSTNAME >> /root/setenv
echo 'export EC2_INSTANCE_ID='$EC2_INSTANCE_ID >> /root/setenv
echo 'export EC2_INSTANCE_TYPE='$EC2_INSTANCE_TYPE >> /root/setenv
echo 'export EC2_LOCAL_HOSTNAME='$EC2_LOCAL_HOSTNAME >> /root/setenv
echo 'export EC2_PUBLIC_HOSTNAME='$EC2_PUBLIC_HOSTNAME >> /root/setenv
echo 'export EC2_PUBLIC_IPV4='$EC2_PUBLIC_IPV4 >> /root/setenv
echo 'export EC2_RESERVATION_ID='$EC2_RESERVATION_ID >> /root/setenv
echo 'export EC2_SECURITY_GROUPS='$EC2_SECURITY_GROUPS >> /root/setenv
echo 'export RS_SERVER='$RS_SERVER >> /root/setenv
echo 'export RS_SKETCHY='$RS_SKETCHY >> /root/setenv
echo 'export RS_TOKEN='$RS_TOKEN >> /root/setenv
chmod 700 /root/setenv

echo $AWS_X509_CERT > /root/cert.pem
echo $AWS_X509_KEY > /root/key.pem 
