#!/bin/bash -e
#
# Copyright (c) 2007-2009 RightScale, Inc, All Rights Reserved Worldwide.
#
#
# Test for a reboot,  if this is a reboot just skip this script.
#

if test "$RS_REBOOT" = "true" ; then
  echo "Skip code install on reboot."
  logger -t RightScale "Skip code install on reboot."
  exit 0 # Leave with a smile ...
fi

## General Variables
deploy_date=$(date "+%Y%m%d%H%M%S")

content_dir=/home/webapps/$APPLICATION_DEFAULT/releases
current_dir=/home/webapps/$APPLICATION_DEFAULT/current
working_dir=$content_dir/working
deploy_dir=$content_dir/$deploy_date

## Apache document root (may not necessarily be the deploy_dir)
apache_doc_pointer=$deploy_dir

## Working directory (may not necessarily be the deploy_dir)
working_dir_pointer=$deploy_dir

## Find out about the old deploy directory
if [ -e $working_dir ]; then
  old_deploy_dir=$(readlink -n $working_dir)
  old_deploy_date=$(basename $old_deploy_dir)
  [ "$old_deploy_dir" == "$content_dir" ] && old_deploy_date=$(basename $(readlink -n $current_dir))
fi

## General Preparation
echo "General Preparation..."
mkdir -p $content_dir
rm -rf $deploy_dir

## Git checkout command
git clone $GIT_REPOSITORY_DEFAULT $deploy_dir

## Release/Deploy date of the APPLICATION_DEFAULT
echo "Prepare to deploy..."
mkdir -p $deploy_dir
chmod 775 $deploy_dir

## Link the Apache document root to the current app dir
echo "Linking the Apache document root to the current/working APPLICATION_DEFAULT directory..."
[ -h $working_dir ] && unlink $working_dir
ln -nfs $working_dir_pointer $working_dir
[ -h $current_dir ] && unlink $current_dir
ln -nfs $apache_doc_pointer $current_dir

