#!/bin/bash
#

DIR=/home/webapps/MeDeploy/current

# Create htpasswd file
htpasswd -bc $DIR/.htpasswd $USERNAME $PASSWORD

# Create htaccess file
cat <<EOF> $DIR/.htaccess
AuthUserFile $DIR/.htpasswd
AuthName "Development"
AuthType Basic
require user $USERNAME
EOF

